let express=require("express")
let mongoose=require ("mongoose")
let routes = require('./routes/monthroute')
let model=require('./model/monthmodel')
let cors=require('cors')
let app=express()
app.use(express.json())
app.use(cors())
mongoose. connect ("mongodb://127.0.0.1:27017/task1").then(()=>{
console. log("database is connected successfully ok")
})
app.use("/",routes) 
app.listen(5000)
